os:
  - linux

sudo: required

language: matlab

matlab:
  - latest

env:
  jobs:
    - USE_NETWORK=true

before_install:
  - sudo apt-get install -y curl

script:
  - matlab -batch "results = runtests('IncludeSubfolders',true); assertSuccess(results);"

