os:
  - linux

sudo: required

env:
  jobs:
    - USE_NETWORK=true

before_install:
  - sudo apt-get install -y curl

script:
  - echo "Printing TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}"
  - curl http://ftp.aiub.unibe.ch/BSWUSER52/GEN/SATELLIT.I14 --output ${TRAVIS_BUILD_DIR}/src/SATELLIT.I14
