os:
  - linux

sudo: required

env:
  jobs:
    - USE_NETWORK=true

before_install:
  - sudo apt-get install -y curl

language: matlab

matlab:
  - latest

script:
  - matlab -batch "results = runtests('IncludeSubfolders',true); assertSuccess(results);"
